### ISSUE TITLE
Fix threading erorr

### ISSUE THREAD

**Issue by EmilyRobotics** [FRC1076/RobotKitLib#25]
`DEBUG:nt.th:Started thread entry-notifier-0
valueChanged: key: 'Disabled'; value: True; isNew: True
valueChanged: key: 'Mode'; value: ; isNew: True
robotdisabled
Traceback (most recent call last):
  File "run.py", line 149, in <module>
    m.mainLoopThread()
  File "run.py", line 100, in mainLoopThread
    self.rl._stop()
  File "/usr/lib/python3.7/threading.py", line 987, in _stop
    assert not lock.locked()
AssertionError`

**Comment by mcolinj** [comment]
So I am going to go back on my original statement that disable should kill the robot thread.   I think you can let the robot thread run, you just need to kill the PWM chip  (through the direct CHIP interface, not through the speed controller).   I think we can probably have a special way to enable/disable the chip, and not have the SpeedController do the enabling at all.     So, we end up not having the threading troubles so much.

It is important that the robot thread runs (so it can talk to the driverstation, so image and sensor processing can continue).   Just need to disable the ability of the robot to drive motors/servos.

I think you *should* diagram the state transitions and actions using FSM (Finite State Machine) UML (Universal Modelling Language?) notation.  It will be a good exercise in doing a robust design that covers all of the cases.    Here's a start:   (pencil and paper are fine, I was just messing around with this tool, since I wanted to share it)

![image](https://user-images.githubusercontent.com/17223153/99480338-e22c1280-2925-11eb-8fa8-cbf71d42a294.png)

You have two state machines (enable/disable)  and the (auton/teleop) machine.    They interact, so you have to capture the dependence between them.
